kind: pipeline
type: docker
name: default

# https://discord.com/api/webhooks/890998423707348993/

steps:
- name: render project charter
  image: docker.io/thomasweise/texlive:latest
  commands:
  - pandoc project-charter.md --from=markdown --to=latex --output=project-charter.pdf --listings --csl=resources/apa.csl --template=resources/eisvogel.latex

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: webhook_id
    webhook_token:
      from_secret: webhook_secret
    username: droneci-bot
    message: hello from droneci cloud